"""Ports: the only surface through which core code reaches the outside world.

Core never imports adapters (ADR-5); adapters implement these Protocols.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import Protocol

from mustrum.core.models import (
    BibEntry,
    Contact,
    ContactLink,
    Embedding,
    EntityKind,
    FetchedMetadata,
    Idea,
    IdeaLink,
    IdeaVersion,
    Match,
    MatchStatus,
    ReadingStatus,
    SearchHit,
    Source,
    SourceText,
    Summary,
)


class LLMProvider(Protocol):
    """Text generation. Output is always untrusted and must be verified (ADR-7)."""

    @property
    def model_name(self) -> str: ...

    def generate(self, prompt: str, *, system: str | None = None) -> str: ...


class EmbeddingProvider(Protocol):
    @property
    def model_name(self) -> str: ...

    def embed(self, texts: Sequence[str]) -> list[tuple[float, ...]]: ...


class MetadataFetcher(Protocol):
    """Fetches authoritative metadata + BibTeX for an identifier (FR-1.2).

    Never synthesises data; raises LookupError if the identifier is unknown.
    """

    def fetch(self, identifier: str) -> FetchedMetadata: ...


class TextExtractor(Protocol):
    def extract(self, path: Path) -> str: ...


class StorageRepo(Protocol):
    """Persistence for all entities. One implementation: SQLite (ADR-2)."""

    # -- sources -----------------------------------------------------------
    def add_source(self, source: Source) -> Source: ...
    def update_source(self, source: Source) -> None: ...
    def get_source(self, source_id: int) -> Source: ...
    def list_sources(self) -> list[Source]: ...
    def find_source_by_doi(self, doi: str) -> Source | None: ...
    def find_source_by_arxiv_id(self, arxiv_id: str) -> Source | None: ...
    def find_source_by_title_hash(self, hash_: str) -> Source | None: ...
    def set_reading_status(self, source_id: int, status: ReadingStatus) -> None: ...
    def set_source_notes(self, source_id: int, notes: str) -> None: ...

    # -- source texts (immutable, ADR-7; controlled upgrade per ADR-9) --------
    def add_source_text(self, text: SourceText) -> None: ...
    def get_source_text(self, source_id: int) -> SourceText | None: ...
    def replace_source_text(self, text: SourceText) -> None: ...

    # -- summaries -----------------------------------------------------------
    def set_summary(self, summary: Summary) -> None: ...
    def get_summary(self, source_id: int) -> Summary | None: ...
    def delete_summary(self, source_id: int) -> None: ...

    # -- ideas ---------------------------------------------------------------
    def add_idea(self, idea: Idea) -> Idea: ...
    def get_idea(self, idea_id: int) -> Idea: ...
    def find_idea_by_title(self, title: str) -> Idea | None: ...
    def list_ideas(self) -> list[Idea]: ...
    def add_idea_version(self, version: IdeaVersion) -> IdeaVersion: ...
    def get_idea_versions(self, idea_id: int) -> list[IdeaVersion]: ...
    def latest_idea_version(self, idea_id: int) -> IdeaVersion | None: ...
    def add_idea_link(self, link: IdeaLink) -> None: ...
    def list_idea_links(self, idea_id: int | None = None) -> list[IdeaLink]: ...

    # -- matches ---------------------------------------------------------------
    def add_match(self, match: Match) -> Match: ...
    def set_match_status(self, match_id: int, status: MatchStatus) -> None: ...
    def list_matches(
        self, idea_id: int | None = None, status: MatchStatus | None = None
    ) -> list[Match]: ...

    # -- bibliography ------------------------------------------------------------
    def set_bib_entry(self, entry: BibEntry) -> None: ...
    def get_bib_entry(self, source_id: int) -> BibEntry | None: ...
    def get_bib_entry_by_key(self, citation_key: str) -> BibEntry | None: ...
    def list_bib_entries(self) -> list[BibEntry]: ...
    def citation_keys(self) -> set[str]: ...

    # -- contacts ------------------------------------------------------------
    def add_contact(self, contact: Contact) -> Contact: ...
    def get_contact(self, contact_id: int) -> Contact: ...
    def list_contacts(self) -> list[Contact]: ...
    def add_contact_link(self, link: ContactLink) -> None: ...
    def list_contact_links(
        self, idea_id: int | None = None, source_id: int | None = None
    ) -> list[ContactLink]: ...

    # -- tags ------------------------------------------------------------------
    def tag(self, entity: EntityKind, ref_id: int, tag: str) -> None: ...
    def untag(self, entity: EntityKind, ref_id: int, tag: str) -> None: ...
    def tags_for(self, entity: EntityKind, ref_id: int) -> set[str]: ...
    def entities_with_tag(self, tag: str) -> list[tuple[EntityKind, int]]: ...

    # -- embeddings ---------------------------------------------------------------
    def store_embeddings(self, embeddings: Sequence[Embedding]) -> None: ...
    def embeddings_for(self, entity: EntityKind, model: str) -> list[Embedding]: ...
    def delete_embeddings(self, entity: EntityKind, ref_id: int) -> None: ...

    # -- search (FR-8.1) -----------------------------------------------------------
    def search(self, query: str, limit: int = 20) -> list[SearchHit]: ...
